### ISSUE TITLE
Consider calling start/stop on root element passed to startAll/stopAll

### ISSUE THREAD

**Issue by mkasperski** [box/t3js#85] opened 2015-06-26 22:44 UTC
Would it be against any of the design choices to change the logic inside `startAll` and `stopAll` to also pick up any module declared on the element passed to those methods (the `root` arg) in addition to child modules found under the `root`?

In our app we have partials that reload and replace themselves; and they sometimes are T3 modules also. While we have the standard `stopAll(elem); loadAndReplace(elem, url); startAll(elem)` cycle implemented, if the author of the partial decides that the module needs to be bound to the `elem`, it won't be picked by the `startAll/stopAll` methods. The alternative is to add an outside wrapper element (mostly not possible in our case, the partial would not know about it) or inner, direct child container and treat it as the module host (however, this container is artificial and is there only as a workaround for chosen javascript library's issue; not mentioning it could mess with css selectors designed for the partial's content). As we're moving our here-and-there js "code islands" progressively to T3 modules, we'd love not to have to change the html structure to make the move possible.

As a bonus, the change would allow declaring modules on the `html` element (referenced as `document.documentElement` in `Box.Application.init/destroy` methods), if anyone so desires.

What do you think abou the proposed change?

**Comment by nzakas** [comment] 2015-06-27 17:29
The reason we dont do that is to discourage modules inside of modules, which is a T3 anti-pattern.

You can, however, accomplish what you want be calling stop() then stopAll() (or vice versa). I'd suggest creating a function that wraps those two calls for convenience.

**Comment by nzakas** [comment] 2015-07-28 17:04
We won't be making a change for this, so closing.

**Closed by nzakas** 2015-07-28 17:04 UTC

**Comment by andreyvolokitin** [comment] 2018-11-08 10:55
> The reason we dont do that is to discourage modules inside of modules, which is a T3 anti-pattern.

@nzakas, are there any "fundamental" reasons to why nested modules are considered an anti-pattern? 

I'm currently trying to reimplement a modified version of T3 which will allow more "granular" modules, and also mixins for modules via multiple module names in `data-module` attribute (I hope to replace behaviors that way also — to reuse a module I'd just mix its name inside appropriate `data-module` attribute). 

Of course, there will be quite a few nested modules, and I'm wondering if there are some hidden obstacles/issues which make nested modules "evil" per se? Or it is more of a restriction appeared due to the way T3 was designed? I want to keep all/most of the principles on which T3 was based, I just want to allow modules to be more granular when it is needed
